[package]
name = "xmrsplayer"
version = "0.6.1"
edition = "2021"
description = "XMrsPlayer is a safe soundtracker music player"
authors = ["Sebastien Bechet"]
documentation = "https://docs.rs/xmrsplayer"
repository = "https://codeberg.org/sbechet/xmrsplayer"

readme = "README.md"
license = "MIT"

keywords = ["xm", "module", "mod", "s3m", "soundtracker"]
categories = ["multimedia::audio", "embedded", "no-std"]

[dependencies]
xmrs = { version= "0.6.1", features = ["std"] }
clap = { version = "4.4", optional = true, features = ["cargo", "derive"] }
rodio =  { version = "0.18", optional = true }
console =  { version = "0.15", optional = true }
cpal =  { version = "0.15", optional = true }

[features]
default = []
demo = ["clap", "rodio", "console", "cpal"]

[lib]
name = "xmrsplayer"
path = "src/lib.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
